const fs=require('node:fs'),crypto=require('node:crypto');
const jobs=require('./jobs.json');
const catalog={weapons:{},extras:{},traits:{},monsters:{},bosses:{},hunters:{},environments:{},menus:{}};
const pending=[],done=[];
const corrections=require('./open-corrections.json');
catalog.reviewPending=corrections.map(c=>c.target);
for(const j of jobs){
 if(!fs.existsSync(j.target)){pending.push(j.id);continue;}
 const record={id:j.id,target:j.target,kind:j.kind,name:j.name,skin:j.skin,features:j.features||[],sha256:crypto.createHash('sha256').update(fs.readFileSync(j.target)).digest('hex')};done.push(record);
 if(j.kind==='weapon'||j.kind==='extra'){const group=catalog[j.kind==='weapon'?'weapons':'extras'];(group[j.name]||={})[j.skin]=j.target;}
 else if(j.kind==='trait')catalog.traits[j.traitId]=j.target;
 else if(j.kind==='hunter')(catalog.hunters[j.tier]||=[])[j.index]=j.target;
 else if(j.kind==='environment')catalog.environments[j.id.replace('environment_','')]=j.target;
 else if(j.kind==='menu')catalog.menus[j.name]=j.target;
 else catalog[j.kind==='boss'?'bosses':'monsters'][j.name]=j.target;
}
// Do not expose holes while production is in progress.
for(const key of Object.keys(catalog.hunters))catalog.hunters[key]=catalog.hunters[key].filter(Boolean);
fs.writeFileSync('ui/art-catalog.js','/* Generated by tools/art-overhaul/compile.cjs. Local paths only. */\nwindow.RPG_HUNT_ART_CATALOG = '+JSON.stringify(catalog,null,2)+';\n');
fs.writeFileSync('tools/art-overhaul/status.json',JSON.stringify({total:jobs.length,completed:done.length,pending,corrections,assets:done},null,2));
console.log('Art catalog:',done.length+'/'+jobs.length,'complete');
