/* Generated by tools/art-overhaul/compile.cjs. Local paths only. */
window.RPG_HUNT_ART_CATALOG = {
  "weapons": {
    "Infantry 73L Bayonet": {
      "standard_darkwood": "assets/overhaul/weapons/infantry_73l_bayonet/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/infantry_73l_bayonet/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/infantry_73l_bayonet/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/infantry_73l_bayonet/bone_ritual.png"
    },
    "Infantry 73L Sniper": {
      "standard_darkwood": "assets/overhaul/weapons/infantry_73l_sniper/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/infantry_73l_sniper/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/infantry_73l_sniper/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/infantry_73l_sniper/bone_ritual.png"
    },
    "Frontier 73C Marksman": {
      "standard_darkwood": "assets/overhaul/weapons/frontier_73c_marksman/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/frontier_73c_marksman/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/frontier_73c_marksman/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/frontier_73c_marksman/bone_ritual.png"
    },
    "Frontier 73C Silencer": {
      "standard_darkwood": "assets/overhaul/weapons/frontier_73c_silencer/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/frontier_73c_silencer/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/frontier_73c_silencer/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/frontier_73c_silencer/bone_ritual.png"
    },
    "LeMat Carbine Marksman": {
      "standard_darkwood": "assets/overhaul/weapons/lemat_carbine_marksman/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/lemat_carbine_marksman/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/lemat_carbine_marksman/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/lemat_carbine_marksman/bone_ritual.png"
    },
    "Officer Carbine Deadeye": {
      "standard_darkwood": "assets/overhaul/weapons/officer_carbine_deadeye/standard_darkwood.png"
    },
    "Bornheim No. 3 Silencer": {
      "standard_darkwood": "assets/overhaul/weapons/bornheim_no_3_silencer/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/bornheim_no_3_silencer/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/bornheim_no_3_silencer/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/bornheim_no_3_silencer/bone_ritual.png"
    },
    "Nagant M1895 Deadeye": {
      "standard_darkwood": "assets/overhaul/weapons/nagant_m1895_deadeye/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/nagant_m1895_deadeye/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/nagant_m1895_deadeye/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/nagant_m1895_deadeye/bone_ritual.png"
    },
    "Nagant M1895 Silencer": {
      "standard_darkwood": "assets/overhaul/weapons/nagant_m1895_silencer/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/nagant_m1895_silencer/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/nagant_m1895_silencer/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/nagant_m1895_silencer/bone_ritual.png"
    },
    "1865 Carbine Silencer": {
      "standard_darkwood": "assets/overhaul/weapons/1865_carbine_silencer/standard_darkwood.png"
    },
    "Centennial Shorty Silencer": {
      "standard_darkwood": "assets/overhaul/weapons/centennial_shorty_silencer/standard_darkwood.png"
    },
    "Centennial Sniper": {
      "standard_darkwood": "assets/overhaul/weapons/centennial_sniper/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/centennial_sniper/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/centennial_sniper/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/centennial_sniper/bone_ritual.png"
    },
    "Maynard Sniper": {
      "standard_darkwood": "assets/overhaul/weapons/maynard_sniper/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/maynard_sniper/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/maynard_sniper/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/maynard_sniper/bone_ritual.png"
    },
    "Maynard Sniper Silencer": {
      "standard_darkwood": "assets/overhaul/weapons/maynard_sniper_silencer/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/maynard_sniper_silencer/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/maynard_sniper_silencer/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/maynard_sniper_silencer/bone_ritual.png"
    },
    "Springfield 1866 Bayonet": {
      "standard_darkwood": "assets/overhaul/weapons/springfield_1866_bayonet/standard_darkwood.png"
    },
    "Springfield 1866 Marksman": {
      "standard_darkwood": "assets/overhaul/weapons/springfield_1866_marksman/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/springfield_1866_marksman/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/springfield_1866_marksman/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/springfield_1866_marksman/bone_ritual.png"
    },
    "Vetterli 71 Bayonet": {
      "standard_darkwood": "assets/overhaul/weapons/vetterli_71_bayonet/standard_darkwood.png"
    },
    "Vetterli 71 Deadeye": {
      "standard_darkwood": "assets/overhaul/weapons/vetterli_71_deadeye/standard_darkwood.png"
    },
    "Vetterli 71 Marksman": {
      "standard_darkwood": "assets/overhaul/weapons/vetterli_71_marksman/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/vetterli_71_marksman/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/vetterli_71_marksman/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/vetterli_71_marksman/bone_ritual.png"
    },
    "Vetterli 71 Silencer": {
      "standard_darkwood": "assets/overhaul/weapons/vetterli_71_silencer/standard_darkwood.png"
    },
    "Martini-Henry Deadeye": {
      "standard_darkwood": "assets/overhaul/weapons/martini_henry_deadeye/standard_darkwood.png"
    },
    "Martini-Henry Marksman": {
      "standard_darkwood": "assets/overhaul/weapons/martini_henry_marksman/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/martini_henry_marksman/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/martini_henry_marksman/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/martini_henry_marksman/bone_ritual.png"
    },
    "Sparks Silencer": {
      "standard_darkwood": "assets/overhaul/weapons/sparks_silencer/standard_darkwood.png"
    },
    "Sparks Sniper": {
      "standard_darkwood": "assets/overhaul/weapons/sparks_sniper/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/sparks_sniper/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/sparks_sniper/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/sparks_sniper/bone_ritual.png"
    },
    "Sparks Pistol Silencer": {
      "standard_darkwood": "assets/overhaul/weapons/sparks_pistol_silencer/standard_darkwood.png"
    },
    "Uppercut Deadeye": {
      "standard_darkwood": "assets/overhaul/weapons/uppercut_deadeye/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/uppercut_deadeye/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/uppercut_deadeye/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/uppercut_deadeye/bone_ritual.png"
    },
    "Berthier 1892 Deadeye": {
      "standard_darkwood": "assets/overhaul/weapons/berthier_1892_deadeye/standard_darkwood.png"
    },
    "Berthier 1892 Marksman": {
      "standard_darkwood": "assets/overhaul/weapons/berthier_1892_marksman/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/berthier_1892_marksman/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/berthier_1892_marksman/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/berthier_1892_marksman/bone_ritual.png"
    },
    "Krag Bayonet": {
      "standard_darkwood": "assets/overhaul/weapons/krag_bayonet/standard_darkwood.png"
    },
    "Krag Silencer": {
      "standard_darkwood": "assets/overhaul/weapons/krag_silencer/standard_darkwood.png"
    },
    "Krag Sniper": {
      "standard_darkwood": "assets/overhaul/weapons/krag_sniper/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/krag_sniper/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/krag_sniper/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/krag_sniper/bone_ritual.png"
    },
    "Lebel 1886 Marksman": {
      "standard_darkwood": "assets/overhaul/weapons/lebel_1886_marksman/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/lebel_1886_marksman/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/lebel_1886_marksman/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/lebel_1886_marksman/bone_ritual.png"
    },
    "Mosin-Nagant Bayonet": {
      "standard_darkwood": "assets/overhaul/weapons/mosin_nagant_bayonet/standard_darkwood.png"
    },
    "Mosin-Nagant Sniper": {
      "standard_darkwood": "assets/overhaul/weapons/mosin_nagant_sniper/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/mosin_nagant_sniper/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/mosin_nagant_sniper/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/mosin_nagant_sniper/bone_ritual.png"
    },
    "Burgess Bayonet": {
      "standard_darkwood": "assets/overhaul/weapons/burgess_bayonet/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/burgess_bayonet/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/burgess_bayonet/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/burgess_bayonet/bone_ritual.png"
    },
    "Specter 1882 Bayonet": {
      "standard_darkwood": "assets/overhaul/weapons/specter_1882_bayonet/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/specter_1882_bayonet/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/specter_1882_bayonet/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/specter_1882_bayonet/bone_ritual.png"
    },
    "Crossbow Deadeye": {
      "standard_darkwood": "assets/overhaul/weapons/crossbow_deadeye/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/crossbow_deadeye/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/crossbow_deadeye/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/crossbow_deadeye/bone_ritual.png"
    },
    "Infantry 73L": {
      "standard_darkwood": "assets/overhaul/weapons/infantry_73l/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/infantry_73l/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/infantry_73l/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/infantry_73l/bone_ritual.png"
    },
    "Marathon": {
      "standard_darkwood": "assets/overhaul/weapons/marathon/standard_darkwood.png"
    },
    "Marathon Swift": {
      "standard_darkwood": "assets/overhaul/weapons/marathon_swift/standard_darkwood.png"
    },
    "Ranger 73": {
      "standard_darkwood": "assets/overhaul/weapons/ranger_73/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/ranger_73/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/ranger_73/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/ranger_73/bone_ritual.png"
    },
    "Ranger 73 Aperture": {
      "standard_darkwood": "assets/overhaul/weapons/ranger_73_aperture/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/ranger_73_aperture/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/ranger_73_aperture/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/ranger_73_aperture/bone_ritual.png"
    },
    "Ranger 73 Swift": {
      "standard_darkwood": "assets/overhaul/weapons/ranger_73_swift/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/ranger_73_swift/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/ranger_73_swift/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/ranger_73_swift/bone_ritual.png"
    },
    "Ranger 73 Talon": {
      "standard_darkwood": "assets/overhaul/weapons/ranger_73_talon/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/ranger_73_talon/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/ranger_73_talon/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/ranger_73_talon/bone_ritual.png"
    },
    "Frontier 73C": {
      "standard_darkwood": "assets/overhaul/weapons/frontier_73c/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/frontier_73c/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/frontier_73c/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/frontier_73c/bone_ritual.png"
    },
    "LeMat": {
      "standard_darkwood": "assets/overhaul/weapons/lemat/standard_darkwood.png"
    },
    "LeMat Carbine": {
      "standard_darkwood": "assets/overhaul/weapons/lemat_carbine/standard_darkwood.png"
    },
    "Officer": {
      "standard_darkwood": "assets/overhaul/weapons/officer/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/officer/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/officer/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/officer/bone_ritual.png"
    },
    "Officer Brawler": {
      "standard_darkwood": "assets/overhaul/weapons/officer_brawler/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/officer_brawler/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/officer_brawler/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/officer_brawler/bone_ritual.png"
    },
    "Officer Carbine": {
      "standard_darkwood": "assets/overhaul/weapons/officer_carbine/standard_darkwood.png"
    },
    "Bornheim No. 3": {
      "standard_darkwood": "assets/overhaul/weapons/bornheim_no_3/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/bornheim_no_3/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/bornheim_no_3/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/bornheim_no_3/bone_ritual.png"
    },
    "Bornheim No. 3 Extended": {
      "standard_darkwood": "assets/overhaul/weapons/bornheim_no_3_extended/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/bornheim_no_3_extended/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/bornheim_no_3_extended/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/bornheim_no_3_extended/bone_ritual.png"
    },
    "Bornheim No. 3 Match": {
      "standard_darkwood": "assets/overhaul/weapons/bornheim_no_3_match/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/bornheim_no_3_match/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/bornheim_no_3_match/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/bornheim_no_3_match/bone_ritual.png"
    },
    "Nagant M1895": {
      "standard_darkwood": "assets/overhaul/weapons/nagant_m1895/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/nagant_m1895/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/nagant_m1895/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/nagant_m1895/bone_ritual.png"
    },
    "Nagant M1895 Precision": {
      "standard_darkwood": "assets/overhaul/weapons/nagant_m1895_precision/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/nagant_m1895_precision/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/nagant_m1895_precision/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/nagant_m1895_precision/bone_ritual.png"
    },
    "Vandal 73C": {
      "standard_darkwood": "assets/overhaul/weapons/vandal_73c/standard_darkwood.png"
    },
    "Vandal 73C Bullseye": {
      "standard_darkwood": "assets/overhaul/weapons/vandal_73c_bullseye/standard_darkwood.png"
    },
    "Vandal 73C Striker": {
      "standard_darkwood": "assets/overhaul/weapons/vandal_73c_striker/standard_darkwood.png"
    },
    "Conversion": {
      "standard_darkwood": "assets/overhaul/weapons/conversion/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/conversion/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/conversion/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/conversion/bone_ritual.png"
    },
    "Conversion Chain Pistol": {
      "standard_darkwood": "assets/overhaul/weapons/conversion_chain_pistol/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/conversion_chain_pistol/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/conversion_chain_pistol/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/conversion_chain_pistol/bone_ritual.png"
    },
    "New Army": {
      "standard_darkwood": "assets/overhaul/weapons/new_army/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/new_army/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/new_army/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/new_army/bone_ritual.png"
    },
    "New Army Swift": {
      "standard_darkwood": "assets/overhaul/weapons/new_army_swift/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/new_army_swift/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/new_army_swift/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/new_army_swift/bone_ritual.png"
    },
    "1865 Carbine": {
      "standard_darkwood": "assets/overhaul/weapons/1865_carbine/standard_darkwood.png"
    },
    "1865 Carbine Aperture": {
      "standard_darkwood": "assets/overhaul/weapons/1865_carbine_aperture/standard_darkwood.png"
    },
    "Centennial": {
      "standard_darkwood": "assets/overhaul/weapons/centennial/standard_darkwood.png"
    },
    "Centennial Pointman": {
      "standard_darkwood": "assets/overhaul/weapons/centennial_pointman/standard_darkwood.png"
    },
    "Centennial Shorty": {
      "standard_darkwood": "assets/overhaul/weapons/centennial_shorty/standard_darkwood.png"
    },
    "Centennial Trauma": {
      "standard_darkwood": "assets/overhaul/weapons/centennial_trauma/standard_darkwood.png"
    },
    "Drilling": {
      "standard_darkwood": "assets/overhaul/weapons/drilling/standard_darkwood.png"
    },
    "Drilling Hatchet": {
      "standard_darkwood": "assets/overhaul/weapons/drilling_hatchet/standard_darkwood.png"
    },
    "Drilling Shorty": {
      "standard_darkwood": "assets/overhaul/weapons/drilling_shorty/standard_darkwood.png"
    },
    "Pax": {
      "standard_darkwood": "assets/overhaul/weapons/pax/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/pax/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/pax/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/pax/bone_ritual.png"
    },
    "Pax Claw": {
      "standard_darkwood": "assets/overhaul/weapons/pax_claw/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/pax_claw/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/pax_claw/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/pax_claw/bone_ritual.png"
    },
    "Pax Trueshot": {
      "standard_darkwood": "assets/overhaul/weapons/pax_trueshot/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/pax_trueshot/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/pax_trueshot/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/pax_trueshot/bone_ritual.png"
    },
    "Scottfield": {
      "standard_darkwood": "assets/overhaul/weapons/scottfield/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/scottfield/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/scottfield/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/scottfield/bone_ritual.png"
    },
    "Scottfield Brawler": {
      "standard_darkwood": "assets/overhaul/weapons/scottfield_brawler/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/scottfield_brawler/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/scottfield_brawler/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/scottfield_brawler/bone_ritual.png"
    },
    "Scottfield Precision": {
      "standard_darkwood": "assets/overhaul/weapons/scottfield_precision/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/scottfield_precision/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/scottfield_precision/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/scottfield_precision/bone_ritual.png"
    },
    "Scottfield Spitfire": {
      "standard_darkwood": "assets/overhaul/weapons/scottfield_spitfire/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/scottfield_spitfire/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/scottfield_spitfire/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/scottfield_spitfire/bone_ritual.png"
    },
    "Scottfield Swift": {
      "standard_darkwood": "assets/overhaul/weapons/scottfield_swift/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/scottfield_swift/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/scottfield_swift/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/scottfield_swift/bone_ritual.png"
    },
    "Springfield 1866": {
      "standard_darkwood": "assets/overhaul/weapons/springfield_1866/standard_darkwood.png"
    },
    "Springfield 1866 Bullseye": {
      "standard_darkwood": "assets/overhaul/weapons/springfield_1866_bullseye/standard_darkwood.png"
    },
    "Springfield 1866 Shorty": {
      "standard_darkwood": "assets/overhaul/weapons/springfield_1866_shorty/standard_darkwood.png"
    },
    "Springfield 1866 Striker": {
      "standard_darkwood": "assets/overhaul/weapons/springfield_1866_striker/standard_darkwood.png"
    },
    "Vetterli 71": {
      "standard_darkwood": "assets/overhaul/weapons/vetterli_71/standard_darkwood.png"
    },
    "Vetterli 71 Cyclone": {
      "standard_darkwood": "assets/overhaul/weapons/vetterli_71_cyclone/standard_darkwood.png"
    },
    "Wildland": {
      "standard_darkwood": "assets/overhaul/weapons/wildland/standard_darkwood.png"
    },
    "1890 Cavalry": {
      "standard_darkwood": "assets/overhaul/weapons/1890_cavalry/standard_darkwood.png"
    },
    "Haymaker": {
      "standard_darkwood": "assets/overhaul/weapons/haymaker/standard_darkwood.png"
    },
    "Mako 1895": {
      "standard_darkwood": "assets/overhaul/weapons/mako_1895/standard_darkwood.png"
    },
    "Mako 1895 Aperture": {
      "standard_darkwood": "assets/overhaul/weapons/mako_1895_aperture/standard_darkwood.png"
    },
    "Mako 1895 Claw": {
      "standard_darkwood": "assets/overhaul/weapons/mako_1895_claw/standard_darkwood.png"
    },
    "Martini-Henry": {
      "standard_darkwood": "assets/overhaul/weapons/martini_henry/standard_darkwood.png"
    },
    "Martini-Henry Ironside": {
      "standard_darkwood": "assets/overhaul/weapons/martini_henry_ironside/standard_darkwood.png"
    },
    "Martini-Henry Riposte": {
      "standard_darkwood": "assets/overhaul/weapons/martini_henry_riposte/standard_darkwood.png"
    },
    "Sparks": {
      "standard_darkwood": "assets/overhaul/weapons/sparks/standard_darkwood.png"
    },
    "Sparks Pistol": {
      "standard_darkwood": "assets/overhaul/weapons/sparks_pistol/standard_darkwood.png"
    },
    "Uppercut": {
      "standard_darkwood": "assets/overhaul/weapons/uppercut/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/uppercut/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/uppercut/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/uppercut/bone_ritual.png"
    },
    "Uppercut Precision": {
      "standard_darkwood": "assets/overhaul/weapons/uppercut_precision/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/uppercut_precision/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/uppercut_precision/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/uppercut_precision/bone_ritual.png"
    },
    "Berthier 1892": {
      "standard_darkwood": "assets/overhaul/weapons/berthier_1892/standard_darkwood.png"
    },
    "Berthier 1892 Riposte": {
      "standard_darkwood": "assets/overhaul/weapons/berthier_1892_riposte/standard_darkwood.png"
    },
    "Krag": {
      "standard_darkwood": "assets/overhaul/weapons/krag/standard_darkwood.png"
    },
    "Lebel 1886": {
      "standard_darkwood": "assets/overhaul/weapons/lebel_1886/standard_darkwood.png"
    },
    "Lebel 1886 Aperture": {
      "standard_darkwood": "assets/overhaul/weapons/lebel_1886_aperture/standard_darkwood.png"
    },
    "Lebel 1886 Talon": {
      "standard_darkwood": "assets/overhaul/weapons/lebel_1886_talon/standard_darkwood.png"
    },
    "Mosin-Nagant": {
      "standard_darkwood": "assets/overhaul/weapons/mosin_nagant/standard_darkwood.png"
    },
    "Mosin-Nagant Avtomat": {
      "standard_darkwood": "assets/overhaul/weapons/mosin_nagant_avtomat/standard_darkwood.png"
    },
    "Mosin Obrez": {
      "standard_darkwood": "assets/overhaul/weapons/mosin_obrez/standard_darkwood.png"
    },
    "Mosin Obrez Extended": {
      "standard_darkwood": "assets/overhaul/weapons/mosin_obrez_extended/standard_darkwood.png"
    },
    "Mosin Obrez Mace": {
      "standard_darkwood": "assets/overhaul/weapons/mosin_obrez_mace/standard_darkwood.png"
    },
    "Mosin Obrez Match": {
      "standard_darkwood": "assets/overhaul/weapons/mosin_obrez_match/standard_darkwood.png"
    },
    "Mosin Obrez Sharpeye": {
      "standard_darkwood": "assets/overhaul/weapons/mosin_obrez_sharpeye/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/mosin_obrez_sharpeye/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/mosin_obrez_sharpeye/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/mosin_obrez_sharpeye/bone_ritual.png"
    },
    "Auto-5": {
      "standard_darkwood": "assets/overhaul/weapons/auto_5/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/auto_5/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/auto_5/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/auto_5/bone_ritual.png"
    },
    "Auto-4 Shorty": {
      "standard_darkwood": "assets/overhaul/weapons/auto_4_shorty/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/auto_4_shorty/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/auto_4_shorty/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/auto_4_shorty/bone_ritual.png"
    },
    "Burgess": {
      "standard_darkwood": "assets/overhaul/weapons/burgess/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/burgess/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/burgess/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/burgess/bone_ritual.png"
    },
    "Burgess Trauma": {
      "standard_darkwood": "assets/overhaul/weapons/burgess_trauma/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/burgess_trauma/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/burgess_trauma/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/burgess_trauma/bone_ritual.png"
    },
    "Homestead 78": {
      "standard_darkwood": "assets/overhaul/weapons/homestead_78/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/homestead_78/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/homestead_78/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/homestead_78/bone_ritual.png"
    },
    "Rival 78": {
      "standard_darkwood": "assets/overhaul/weapons/rival_78/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/rival_78/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/rival_78/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/rival_78/bone_ritual.png"
    },
    "Rival 78 Mace": {
      "standard_darkwood": "assets/overhaul/weapons/rival_78_mace/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/rival_78_mace/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/rival_78_mace/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/rival_78_mace/bone_ritual.png"
    },
    "Rival 78 Shorty": {
      "standard_darkwood": "assets/overhaul/weapons/rival_78_shorty/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/rival_78_shorty/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/rival_78_shorty/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/rival_78_shorty/bone_ritual.png"
    },
    "Rival 78 Trauma": {
      "standard_darkwood": "assets/overhaul/weapons/rival_78_trauma/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/rival_78_trauma/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/rival_78_trauma/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/rival_78_trauma/bone_ritual.png"
    },
    "Romero 77": {
      "standard_darkwood": "assets/overhaul/weapons/romero_77/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/romero_77/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/romero_77/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/romero_77/bone_ritual.png"
    },
    "Romero 77 Alamo": {
      "standard_darkwood": "assets/overhaul/weapons/romero_77_alamo/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/romero_77_alamo/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/romero_77_alamo/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/romero_77_alamo/bone_ritual.png"
    },
    "Romero 77 Hatchet": {
      "standard_darkwood": "assets/overhaul/weapons/romero_77_hatchet/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/romero_77_hatchet/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/romero_77_hatchet/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/romero_77_hatchet/bone_ritual.png"
    },
    "Romero 77 Shorty": {
      "standard_darkwood": "assets/overhaul/weapons/romero_77_shorty/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/romero_77_shorty/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/romero_77_shorty/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/romero_77_shorty/bone_ritual.png"
    },
    "Romero 77 Talon": {
      "standard_darkwood": "assets/overhaul/weapons/romero_77_talon/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/romero_77_talon/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/romero_77_talon/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/romero_77_talon/bone_ritual.png"
    },
    "Slate": {
      "standard_darkwood": "assets/overhaul/weapons/slate/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/slate/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/slate/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/slate/bone_ritual.png"
    },
    "Slate Riposte": {
      "standard_darkwood": "assets/overhaul/weapons/slate_riposte/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/slate_riposte/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/slate_riposte/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/slate_riposte/bone_ritual.png"
    },
    "Specter 1882": {
      "standard_darkwood": "assets/overhaul/weapons/specter_1882/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/specter_1882/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/specter_1882/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/specter_1882/bone_ritual.png"
    },
    "Specter 1882 Shorty": {
      "standard_darkwood": "assets/overhaul/weapons/specter_1882_shorty/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/specter_1882_shorty/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/specter_1882_shorty/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/specter_1882_shorty/bone_ritual.png"
    },
    "Terminus": {
      "standard_darkwood": "assets/overhaul/weapons/terminus/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/terminus/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/terminus/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/terminus/bone_ritual.png"
    },
    "Terminus Shorty": {
      "standard_darkwood": "assets/overhaul/weapons/terminus_shorty/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/terminus_shorty/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/terminus_shorty/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/terminus_shorty/bone_ritual.png"
    },
    "Bomb Launcher": {
      "standard_darkwood": "assets/overhaul/weapons/bomb_launcher/standard_darkwood.png"
    },
    "Bomb Lance": {
      "standard_darkwood": "assets/overhaul/weapons/bomb_lance/standard_darkwood.png"
    },
    "Chu Ko Nu": {
      "standard_darkwood": "assets/overhaul/weapons/chu_ko_nu/standard_darkwood.png"
    },
    "Crossbow": {
      "standard_darkwood": "assets/overhaul/weapons/crossbow/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/crossbow/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/crossbow/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/crossbow/bone_ritual.png"
    },
    "Dolch 96": {
      "standard_darkwood": "assets/overhaul/weapons/dolch_96/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/dolch_96/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/dolch_96/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/dolch_96/bone_ritual.png"
    },
    "Dolch 96 Claw": {
      "standard_darkwood": "assets/overhaul/weapons/dolch_96_claw/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/dolch_96_claw/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/dolch_96_claw/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/dolch_96_claw/bone_ritual.png"
    },
    "Dolch 96 Bullseye": {
      "standard_darkwood": "assets/overhaul/weapons/dolch_96_bullseye/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/weapons/dolch_96_bullseye/bayou_wrap.png",
      "elite_brass": "assets/overhaul/weapons/dolch_96_bullseye/elite_brass.png",
      "bone_ritual": "assets/overhaul/weapons/dolch_96_bullseye/bone_ritual.png"
    },
    "Dolch 96 Precision": {
      "standard_darkwood": "assets/overhaul/weapons/dolch_96_precision/standard_darkwood.png"
    },
    "Hunting Bow": {
      "standard_darkwood": "assets/overhaul/weapons/hunting_bow/standard_darkwood.png"
    },
    "Hand Crossbow": {
      "standard_darkwood": "assets/overhaul/weapons/hand_crossbow/standard_darkwood.png"
    },
    "Nitro Express": {
      "standard_darkwood": "assets/overhaul/weapons/nitro_express/standard_darkwood.png"
    },
    "Shredder": {
      "standard_darkwood": "assets/overhaul/weapons/shredder/standard_darkwood.png"
    },
    "Flame Rifle": {
      "standard_darkwood": "assets/overhaul/weapons/flame_rifle/standard_darkwood.png"
    },
    "Baseball Bat": {
      "standard_darkwood": "assets/overhaul/weapons/baseball_bat/standard_darkwood.png"
    },
    "Cavalry Saber": {
      "standard_darkwood": "assets/overhaul/weapons/cavalry_saber/standard_darkwood.png"
    },
    "Combat Axe": {
      "standard_darkwood": "assets/overhaul/weapons/combat_axe/standard_darkwood.png"
    },
    "Katana": {
      "standard_darkwood": "assets/overhaul/weapons/katana/standard_darkwood.png"
    },
    "Machete": {
      "standard_darkwood": "assets/overhaul/weapons/machete/standard_darkwood.png"
    },
    "Railroad Hammer": {
      "standard_darkwood": "assets/overhaul/weapons/railroad_hammer/standard_darkwood.png"
    }
  },
  "extras": {
    "Dusters": {
      "standard_darkwood": "assets/overhaul/extras/dusters/standard_darkwood.png"
    },
    "Knife": {
      "standard_darkwood": "assets/overhaul/extras/knife/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/extras/knife/bayou_wrap.png",
      "elite_brass": "assets/overhaul/extras/knife/elite_brass.png",
      "bone_ritual": "assets/overhaul/extras/knife/bone_ritual.png"
    },
    "Heavy Knife": {
      "standard_darkwood": "assets/overhaul/extras/heavy_knife/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/extras/heavy_knife/bayou_wrap.png",
      "elite_brass": "assets/overhaul/extras/heavy_knife/elite_brass.png",
      "bone_ritual": "assets/overhaul/extras/heavy_knife/bone_ritual.png"
    },
    "Knuckle Knife": {
      "standard_darkwood": "assets/overhaul/extras/knuckle_knife/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/extras/knuckle_knife/bayou_wrap.png",
      "elite_brass": "assets/overhaul/extras/knuckle_knife/elite_brass.png",
      "bone_ritual": "assets/overhaul/extras/knuckle_knife/bone_ritual.png"
    },
    "Throwing Knives": {
      "standard_darkwood": "assets/overhaul/extras/throwing_knives/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/extras/throwing_knives/bayou_wrap.png",
      "elite_brass": "assets/overhaul/extras/throwing_knives/elite_brass.png",
      "bone_ritual": "assets/overhaul/extras/throwing_knives/bone_ritual.png"
    },
    "Throwing Axes": {
      "standard_darkwood": "assets/overhaul/extras/throwing_axes/standard_darkwood.png",
      "bayou_wrap": "assets/overhaul/extras/throwing_axes/bayou_wrap.png",
      "elite_brass": "assets/overhaul/extras/throwing_axes/elite_brass.png",
      "bone_ritual": "assets/overhaul/extras/throwing_axes/bone_ritual.png"
    },
    "Throwing Spear": {
      "standard_darkwood": "assets/overhaul/extras/throwing_spear/standard_darkwood.png"
    },
    "Quad Derringer": {
      "standard_darkwood": "assets/overhaul/extras/quad_derringer/standard_darkwood.png"
    },
    "Derringer Pennyshot": {
      "standard_darkwood": "assets/overhaul/extras/derringer_pennyshot/standard_darkwood.png"
    },
    "Decoys": {
      "standard_darkwood": "assets/overhaul/extras/decoys/standard_darkwood.png"
    },
    "Blank Fire Decoys": {
      "standard_darkwood": "assets/overhaul/extras/blank_fire_decoys/standard_darkwood.png"
    },
    "Decoy Fuses": {
      "standard_darkwood": "assets/overhaul/extras/decoy_fuses/standard_darkwood.png"
    },
    "Fusees": {
      "standard_darkwood": "assets/overhaul/extras/fusees/standard_darkwood.png"
    },
    "Flare Pistol": {
      "standard_darkwood": "assets/overhaul/extras/flare_pistol/standard_darkwood.png"
    },
    "Alert Trip Mine": {
      "standard_darkwood": "assets/overhaul/extras/alert_trip_mine/standard_darkwood.png"
    },
    "Concertina Trip Mine": {
      "standard_darkwood": "assets/overhaul/extras/concertina_trip_mine/standard_darkwood.png"
    },
    "Poison Trip Mine": {
      "standard_darkwood": "assets/overhaul/extras/poison_trip_mine/standard_darkwood.png"
    },
    "Bear Trap": {
      "standard_darkwood": "assets/overhaul/extras/bear_trap/standard_darkwood.png"
    },
    "First Aid Kit": {
      "standard_darkwood": "assets/overhaul/extras/first_aid_kit/standard_darkwood.png"
    },
    "Choke Bombs": {
      "standard_darkwood": "assets/overhaul/extras/choke_bombs/standard_darkwood.png"
    },
    "Spyglass": {
      "standard_darkwood": "assets/overhaul/extras/spyglass/standard_darkwood.png"
    },
    "Medical Pack": {
      "standard_darkwood": "assets/overhaul/extras/medical_pack/standard_darkwood.png"
    },
    "Weak Vitality Shot": {
      "standard_darkwood": "assets/overhaul/extras/weak_vitality_shot/standard_darkwood.png"
    },
    "Vitality Shot": {
      "standard_darkwood": "assets/overhaul/extras/vitality_shot/standard_darkwood.png"
    },
    "Recovery Shot": {
      "standard_darkwood": "assets/overhaul/extras/recovery_shot/standard_darkwood.png"
    },
    "Weak Regeneration Shot": {
      "standard_darkwood": "assets/overhaul/extras/weak_regeneration_shot/standard_darkwood.png"
    },
    "Regeneration Shot": {
      "standard_darkwood": "assets/overhaul/extras/regeneration_shot/standard_darkwood.png"
    },
    "Weak Antidote Shot": {
      "standard_darkwood": "assets/overhaul/extras/weak_antidote_shot/standard_darkwood.png"
    },
    "Antidote Shot": {
      "standard_darkwood": "assets/overhaul/extras/antidote_shot/standard_darkwood.png"
    },
    "Weak Stamina Shot": {
      "standard_darkwood": "assets/overhaul/extras/weak_stamina_shot/standard_darkwood.png"
    },
    "Stamina Shot": {
      "standard_darkwood": "assets/overhaul/extras/stamina_shot/standard_darkwood.png"
    },
    "Ammo Box": {
      "standard_darkwood": "assets/overhaul/extras/ammo_box/standard_darkwood.png"
    },
    "Tool Box": {
      "standard_darkwood": "assets/overhaul/extras/tool_box/standard_darkwood.png"
    },
    "Dynamite Stick": {
      "standard_darkwood": "assets/overhaul/extras/dynamite_stick/standard_darkwood.png"
    },
    "Waxed Dynamite Stick": {
      "standard_darkwood": "assets/overhaul/extras/waxed_dynamite_stick/standard_darkwood.png"
    },
    "Dynamite Bundle": {
      "standard_darkwood": "assets/overhaul/extras/dynamite_bundle/standard_darkwood.png"
    },
    "Big Dynamite Bundle": {
      "standard_darkwood": "assets/overhaul/extras/big_dynamite_bundle/standard_darkwood.png"
    },
    "Sticky Bomb": {
      "standard_darkwood": "assets/overhaul/extras/sticky_bomb/standard_darkwood.png"
    },
    "Frag Bomb": {
      "standard_darkwood": "assets/overhaul/extras/frag_bomb/standard_darkwood.png"
    },
    "Dark Dynamite Satchel": {
      "standard_darkwood": "assets/overhaul/extras/dark_dynamite_satchel/standard_darkwood.png"
    },
    "Fire Bomb": {
      "standard_darkwood": "assets/overhaul/extras/fire_bomb/standard_darkwood.png"
    },
    "Liquid Fire Bomb": {
      "standard_darkwood": "assets/overhaul/extras/liquid_fire_bomb/standard_darkwood.png"
    },
    "Hellfire Bomb": {
      "standard_darkwood": "assets/overhaul/extras/hellfire_bomb/standard_darkwood.png"
    },
    "Poison Bomb": {
      "standard_darkwood": "assets/overhaul/extras/poison_bomb/standard_darkwood.png"
    },
    "Hive Bomb": {
      "standard_darkwood": "assets/overhaul/extras/hive_bomb/standard_darkwood.png"
    },
    "Flash Bomb": {
      "standard_darkwood": "assets/overhaul/extras/flash_bomb/standard_darkwood.png"
    },
    "Concertina Bomb": {
      "standard_darkwood": "assets/overhaul/extras/concertina_bomb/standard_darkwood.png"
    },
    "Chaos Bomb": {
      "standard_darkwood": "assets/overhaul/extras/chaos_bomb/standard_darkwood.png"
    },
    "Stalker Beetle": {
      "standard_darkwood": "assets/overhaul/extras/stalker_beetle/standard_darkwood.png"
    },
    "Choke Beetle": {
      "standard_darkwood": "assets/overhaul/extras/choke_beetle/standard_darkwood.png"
    },
    "Fire Beetle": {
      "standard_darkwood": "assets/overhaul/extras/fire_beetle/standard_darkwood.png"
    }
  },
  "traits": {
    "0": "assets/overhaul/traits/trait_00_assailant.png",
    "1": "assets/overhaul/traits/trait_01_berserker.png",
    "2": "assets/overhaul/traits/trait_02_bolt_thrower.png",
    "3": "assets/overhaul/traits/trait_03_fanning.png",
    "4": "assets/overhaul/traits/trait_04_fast_fingers.png",
    "5": "assets/overhaul/traits/trait_05_hundred_hands.png",
    "6": "assets/overhaul/traits/trait_06_iron_eye.png",
    "7": "assets/overhaul/traits/trait_07_levering.png",
    "8": "assets/overhaul/traits/trait_08_martialist.png",
    "9": "assets/overhaul/traits/trait_09_pitcher.png",
    "10": "assets/overhaul/traits/trait_10_scopesmith.png",
    "11": "assets/overhaul/traits/trait_11_steady_aim.png",
    "12": "assets/overhaul/traits/trait_12_adrenaline.png",
    "13": "assets/overhaul/traits/trait_13_bloodless.png",
    "14": "assets/overhaul/traits/trait_14_bulwark.png",
    "15": "assets/overhaul/traits/trait_15_dauntless.png",
    "16": "assets/overhaul/traits/trait_16_doctor.png",
    "17": "assets/overhaul/traits/trait_17_hornskin.png",
    "18": "assets/overhaul/traits/trait_18_mithridatist.png",
    "19": "assets/overhaul/traits/trait_19_physician.png",
    "20": "assets/overhaul/traits/trait_20_salveskin.png",
    "21": "assets/overhaul/traits/trait_21_vigor.png",
    "22": "assets/overhaul/traits/trait_22_gator_legs.png",
    "23": "assets/overhaul/traits/trait_23_greyhound.png",
    "24": "assets/overhaul/traits/trait_24_kiteskin.png",
    "25": "assets/overhaul/traits/trait_25_lightfoot.png",
    "26": "assets/overhaul/traits/trait_26_shadow_leap.png",
    "27": "assets/overhaul/traits/trait_27_surefoot.png",
    "28": "assets/overhaul/traits/trait_28_ambidextrous.png",
    "29": "assets/overhaul/traits/trait_29_beastface.png",
    "30": "assets/overhaul/traits/trait_30_blade_seer.png",
    "31": "assets/overhaul/traits/trait_31_blast_sense.png",
    "32": "assets/overhaul/traits/trait_32_bulletgrubber.png",
    "33": "assets/overhaul/traits/trait_33_catalyst.png",
    "34": "assets/overhaul/traits/trait_34_conduit.png",
    "35": "assets/overhaul/traits/trait_35_death_cheat.png",
    "36": "assets/overhaul/traits/trait_36_decoy_supply.png",
    "37": "assets/overhaul/traits/trait_37_determination.png",
    "38": "assets/overhaul/traits/trait_38_frontiersman.png",
    "39": "assets/overhaul/traits/trait_39_ghoul.png",
    "40": "assets/overhaul/traits/trait_40_magpie.png",
    "41": "assets/overhaul/traits/trait_41_necromancer.png",
    "42": "assets/overhaul/traits/trait_42_packmule.png",
    "43": "assets/overhaul/traits/trait_43_pain_sense.png",
    "44": "assets/overhaul/traits/trait_44_poacher.png",
    "45": "assets/overhaul/traits/trait_45_poltergeist.png",
    "46": "assets/overhaul/traits/trait_46_quartermaster.png",
    "47": "assets/overhaul/traits/trait_47_rampage.png",
    "48": "assets/overhaul/traits/trait_48_relentless.png",
    "49": "assets/overhaul/traits/trait_49_remedy.png",
    "50": "assets/overhaul/traits/trait_50_resilience.png",
    "51": "assets/overhaul/traits/trait_51_serpent.png",
    "52": "assets/overhaul/traits/trait_52_shadow.png",
    "53": "assets/overhaul/traits/trait_53_silent_killer.png",
    "54": "assets/overhaul/traits/trait_54_vigilant.png",
    "55": "assets/overhaul/traits/trait_55_vulture.png",
    "56": "assets/overhaul/traits/trait_56_whispersmith.png",
    "57": "assets/overhaul/traits/trait_57_witness.png",
    "58": "assets/overhaul/traits/trait_58_siphon.png",
    "59": "assets/overhaul/traits/trait_59_chupacabra.png",
    "60": "assets/overhaul/traits/trait_60_acolyte.png",
    "61": "assets/overhaul/traits/trait_61_blademancer.png",
    "62": "assets/overhaul/traits/trait_62_bruiser.png",
    "63": "assets/overhaul/traits/trait_63_blazeborne.png",
    "64": "assets/overhaul/traits/trait_64_communion.png",
    "65": "assets/overhaul/traits/trait_65_corpse_seer.png",
    "66": "assets/overhaul/traits/trait_66_crack_shot.png",
    "67": "assets/overhaul/traits/trait_67_final_gasp.png",
    "68": "assets/overhaul/traits/trait_68_fire_eater.png",
    "69": "assets/overhaul/traits/trait_69_flame_touched.png",
    "70": "assets/overhaul/traits/trait_70_gunrunner.png",
    "71": "assets/overhaul/traits/trait_71_indomitable.png",
    "72": "assets/overhaul/traits/trait_72_instinct.png",
    "73": "assets/overhaul/traits/trait_73_mariner.png",
    "74": "assets/overhaul/traits/trait_74_peacekeeper.png",
    "75": "assets/overhaul/traits/trait_75_shadow_crush.png",
    "76": "assets/overhaul/traits/trait_76_signee.png",
    "77": "assets/overhaul/traits/trait_77_all_ears.png",
    "78": "assets/overhaul/traits/trait_78_deadeye_scopesmith.png",
    "79": "assets/overhaul/traits/trait_79_dewclaw.png",
    "80": "assets/overhaul/traits/trait_80_iron_devastator.png",
    "81": "assets/overhaul/traits/trait_81_iron_repeater.png",
    "82": "assets/overhaul/traits/trait_82_iron_sharpshooter.png",
    "83": "assets/overhaul/traits/trait_83_marksman_scopesmith.png",
    "84": "assets/overhaul/traits/trait_84_sniper_scopesmith.png",
    "85": "assets/overhaul/traits/trait_85_steady_hand.png",
    "86": "assets/overhaul/traits/trait_86_tomahawk.png"
  },
  "monsters": {
    "Grunt": "assets/overhaul/monsters/grunt.png",
    "Knife Grunt": "assets/overhaul/monsters/knife_grunt.png",
    "Doctor Grunt": "assets/overhaul/monsters/doctor_grunt.png",
    "Torch Grunt": "assets/overhaul/monsters/torch_grunt.png",
    "Armored": "assets/overhaul/monsters/armored.png",
    "Concertina Armored": "assets/overhaul/monsters/concertina_armored.png",
    "Immolator": "assets/overhaul/monsters/immolator.png",
    "Firebreather": "assets/overhaul/monsters/firebreather.png",
    "Hive": "assets/overhaul/monsters/hive.png",
    "Hive Swarm": "assets/overhaul/monsters/hive_swarm.png",
    "Water Devil": "assets/overhaul/monsters/water_devil.png",
    "Hellhound": "assets/overhaul/monsters/hellhound.png",
    "Bileweaver": "assets/overhaul/monsters/bileweaver.png",
    "Brute": "assets/overhaul/monsters/brute.png",
    "Ursa Mortis": "assets/overhaul/monsters/ursa_mortis.png",
    "Meathead": "assets/overhaul/monsters/meathead.png"
  },
  "bosses": {
    "Butcher": "assets/overhaul/bosses/butcher.png",
    "Spider": "assets/overhaul/bosses/spider.png",
    "Assassin": "assets/overhaul/bosses/assassin.png",
    "Scrapbeak": "assets/overhaul/bosses/scrapbeak.png",
    "Rotjaw": "assets/overhaul/bosses/rotjaw.png",
    "Hellborn": "assets/overhaul/bosses/hellborn.png"
  },
  "hunters": {
    "Standard": [
      "assets/overhaul/hunters/standard_0.png",
      "assets/overhaul/hunters/standard_1.png",
      "assets/overhaul/hunters/standard_2.png",
      "assets/overhaul/hunters/standard_3.png"
    ],
    "Verbessert": [
      "assets/overhaul/hunters/verbessert_0.png",
      "assets/overhaul/hunters/verbessert_1.png",
      "assets/overhaul/hunters/verbessert_2.png",
      "assets/overhaul/hunters/verbessert_3.png"
    ],
    "Elite": [
      "assets/overhaul/hunters/elite_0.png",
      "assets/overhaul/hunters/elite_1.png",
      "assets/overhaul/hunters/elite_2.png",
      "assets/overhaul/hunters/elite_3.png"
    ],
    "Meister": [
      "assets/overhaul/hunters/meister_0.png",
      "assets/overhaul/hunters/meister_1.png",
      "assets/overhaul/hunters/meister_2.png",
      "assets/overhaul/hunters/meister_3.png"
    ]
  },
  "environments": {
    "marsh": "assets/overhaul/environments/marsh.png",
    "farm": "assets/overhaul/environments/farm.png",
    "church": "assets/overhaul/environments/church.png",
    "mine": "assets/overhaul/environments/mine.png",
    "rail": "assets/overhaul/environments/rail.png",
    "swamp": "assets/overhaul/environments/swamp.png",
    "cem": "assets/overhaul/environments/cem.png",
    "compound": "assets/overhaul/environments/compound.png"
  },
  "menus": {
    "recruitment": "assets/overhaul/menu/recruitment.png",
    "arsenal": "assets/overhaul/menu/arsenal.png",
    "gear": "assets/overhaul/menu/gear.png",
    "shop": "assets/overhaul/menu/shop.png",
    "traits": "assets/overhaul/menu/traits.png",
    "codex": "assets/overhaul/menu/codex.png"
  },
  "reviewPending": [
    "assets/overhaul/weapons/terminus_shorty/bayou_wrap.png"
  ]
};
