/* RPG Hunt v0.6: presentation and navigation. Rules remain in game.js. */
window.RPG_HUNT_UI = function installPlayerUI(G, legacy) {
  'use strict';
  const D=window.GAME_DATA,V=window.RPG_HUNT_V3,S=window.RPG_HUNT_SKINS;
  const $=s=>document.querySelector(s);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const cash=n=>Math.round(n||0).toLocaleString('de-DE')+' $';
  const btn=(text,attrs='',disabled=false)=>`<button class="btn secondary" ${attrs} ${disabled?'disabled':''}>${text}</button>`;
  const title=(k,t,sub='')=>`<header class="v6-title"><p class="eyebrow">${k}</p><h1>${t}</h1><p>${sub}</p></header>`;
  const empty=t=>`<div class="empty-state">${t}</div>`;
  let view='hq',history=[],index=0,shopIndex=0,shopMode='weapons',stashMode='weapons',extraType='all',replacement=null;
  let confirmation=null;
  const routes={hq:'Hauptquartier',hunters:'Hunter',recruit:'Rekrutierung',roster:'Hunter-Auswahl',hunterDetail:'Hunter-Details',gear:'Ausrüstung',loadout:'Loadout',armory:'Arsenal',stash:'Lager',shop:'Händler',traits:'Traits',mission:'Mission',codex:'Kodex',stats:'Statistik',settings:'Einstellungen'};
  for(const name of ['stash','stats']){const section=document.createElement('section');section.id='screen-'+name;section.className='screen';$('#app').append(section);}
  const tiles=[['mission','01 / AUFTRAG','Mission','Die Jagd beginnt hier.',V.environments[0].art],['hunters','02 / PERSONAL','Hunter','Deine Mannschaft.',V.menuArt.hunters],['recruit','03 / VERSTÄRKUNG','Rekrutierung','Vier neue Gesichter.',V.menuArt.recruit],['gear','04 / VORBEREITUNG','Ausrüstung','Jeder Slot zählt.',V.menuArt.gear],['shop','05 / BLACKWATER','Händler','Waffen und Vorräte.',V.menuArt.shop],['armory','06 / WAFFENKAMMER','Arsenal','150 Wege zu überleben.',V.menuArt.weaponCarousel],['stash','07 / BESITZ','Lager','Deine gesicherte Ausrüstung.',V.menuArt.merchant],['traits','08 / ERFAHRUNG','Traits','Stärken, die bleiben.',V.menuArt.codex],['codex','09 / WISSEN','Kodex','Kenne deine Beute.',V.bossArt.Butcher],['stats','10 / JAGDBUCH','Statistik','Was die Jagd hinterlässt.',V.environments[3].art],['settings','11 / SYSTEM','Einstellungen','Lokale Spielstände und Optionen.',V.menuArt.settings]];
  const menuNames={mission:'mission',hunters:'hunters',recruit:'recruitment',gear:'gear',shop:'shop',armory:'arsenal',stash:'stash',traits:'traits',codex:'codex',stats:'stats',settings:'settings'};
  const menuImage=id=>window.RPG_HUNT_ART?.menu(id)||`assets/ui/menu/menu_${menuNames[id]||'hunters'}.png`;
  tiles.forEach(t=>t[4]=menuImage(t[0]));
  Object.assign(V.menuArt,{mission:menuImage('mission'),hunters:menuImage('hunters'),recruit:menuImage('recruit'),roster:menuImage('hunters'),gear:menuImage('gear'),shop:menuImage('shop'),weaponCarousel:menuImage('armory'),merchant:menuImage('stash'),codex:menuImage('codex'),settings:menuImage('settings'),missionteam:menuImage('mission')});
  document.querySelectorAll('.menu-tile[data-nav]').forEach(tile=>tile.style.setProperty('--art',`url('${menuImage(tile.dataset.nav==='roster'?'hunters':tile.dataset.nav)}')`));
  function decorateMenu(){
    const id=({roster:'hunters',hunterDetail:'hunters',loadout:'gear'})[view]||view;
    const section=$('#screen-'+view);if(!section||view==='hq')return;
    const existing=section.querySelector('.screen-hero,.shop-hero');
    if(existing){existing.style.setProperty('--hero',`url('${menuImage(id)}')`);return;}
    const heading=section.querySelector(':scope > .section-title,:scope > .v6-title');
    if(heading){heading.classList.add('v6-menu-banner');heading.style.backgroundImage=`url('${menuImage(id)}')`;return;}
    let banner=section.querySelector('.v6-menu-banner');
    if(!banner){banner=document.createElement('div');banner.className='v6-menu-banner';section.prepend(banner);}
    banner.style.backgroundImage=`url('${menuImage(id)}')`;
    banner.innerHTML=`<div><p class="eyebrow">BLACKWATER / HUNTER-QUARTIER</p><h2>${routes[view]}</h2><p>${tiles.find(t=>t[0]===id)?.[3]||'Bereit für die nächste Jagd.'}</p></div>`;
    banner.hidden=!!G.state.run&&view==='mission';
  }
  function skinPicker(w){
    if(!w||!S?.group(w))return '';
    const selected=S.selected(G.state,w),entry=S.get(G.state,w),skin={...selected,description:selected.description+(S.previewAvailable(G.state,w)?'':' Vorschau derzeit im Standard-Look.')};
    return `<div class="v6-skin-picker" aria-label="Waffenskin"><button class="btn secondary" data-v6-skin="-1" data-skin-weapon="${esc(w.name)}" aria-label="Vorheriger Skin" ${entry.ownedSkins.length<2?'disabled':''}>‹</button><div aria-live="polite"><small>${esc(skin.tier)} · KOSMETIK</small><b>${esc(skin.name)}</b><p>${esc(skin.description)}</p><small>${entry.ownedSkins.indexOf(skin.id)+1} / ${entry.ownedSkins.length} · Kostenlos · Alle Exemplare dieses Modells</small></div><button class="btn secondary" data-v6-skin="1" data-skin-weapon="${esc(w.name)}" aria-label="Nächster Skin" ${entry.ownedSkins.length<2?'disabled':''}>›</button></div>`;
  }
  $('#screen-hq .menu-grid').innerHTML=tiles.map(([id,k,n,d,art])=>`<button class="menu-tile ${id==='mission'?'wide':''}" data-nav="${id}" style="--art:url('${art}')"><span class="tile-kicker">${k}</span><strong>${n}</strong><small>${d}</small><span class="tile-arrow" aria-hidden="true">↗</span></button>`).join('');
  $('#screen-hq .hq-hero').style.backgroundImage=`url('${menuImage('mission')}')`;
  $('#screen-hq .hq-hero').innerHTML=`<div class="hero-fade"></div><div class="hero-content"><p class="eyebrow">BLACKWATER · HUNTER-QUARTIER</p><h1>Die Nacht<br>gehört niemandem.</h1><p>Wähle deine Hunter. Prüfe deine Ausrüstung.<br>Und bring sie wieder nach Hause.</p><div class="hero-actions"><button class="btn primary xl" data-nav="mission">Zur Mission <span aria-hidden="true">→</span></button><button class="btn ghost" data-nav="roster">Team zusammenstellen</button></div></div><div class="v6-seal"><span>RH</span><small>HUB & ARSENAL<br>VOL. 06 / PLAYER</small></div>`;
  $('#screen-hunters .submenu-grid').insertAdjacentHTML('beforebegin','<div id="hunterHubCards" class="v6-roster-preview"></div>');
  $('#screen-recruit').insertAdjacentHTML('beforeend','<footer class="v6-recruit-footer"></footer>');
  $('#screen-recruit .v6-recruit-footer').append($('#rerollHunters'));
  $('#rerollHunters').textContent='Neue Rekruten · 100 $';
  $('#screen-armory .armory-toolbar').insertAdjacentHTML('beforeend','<select id="weaponSort" aria-label="Waffen sortieren"><option value="price">Preis aufsteigend</option><option value="damage">Schaden absteigend</option><option value="accuracy">Präzision absteigend</option><option value="quality">Qualität</option></select><select id="weaponFamily" aria-label="Waffengruppe"><option value="all">Alle Waffengruppen</option><option value="pistols">Pistolen</option><option value="rifles">Gewehre</option><option value="shotguns">Schrotflinten</option><option value="special">Spezial</option><option value="melee">Nahkampf</option></select><select id="weaponSource" aria-label="Waffenquelle"><option value="all">Gesamtes Arsenal</option><option value="owned">Nur Lagerbestand</option></select>');
  $('#screen-shop .shop-tabs').innerHTML=['weapons','tools','consumables','ammo','offers'].map((m,i)=>btn(['Waffen','Tools','Consumables','Munition','Auswahl'][i],`data-v6-shop="${m}"`)).join('');
  $('#shopSlot').classList.add('hidden');
  $('#screen-shop .shop-hero-copy p:last-child').textContent='Kaufe ins gemeinsame Lager. Rüste deine Hunter danach ohne weitere Kosten aus.';
  const controls=['weaponSearch','weaponCategory','weaponQuality','weaponSort','weaponFamily','weaponSource'];
  controls.forEach(id=>$('#'+id).addEventListener(id==='weaponSearch'?'input':'change',()=>{index=0;renderArmory();}));

  function selectHunter(id){G.state.activeHunterId=id;G.context={...G.context,hunterId:id};}
  function navigate(next,ctx={},push=true){
    if(!routes[next])return;
    if(G.state.run&&!['hq','mission','codex','stats','settings'].includes(next)){G.toast('Mission läuft. Ausrüstung und Team sind bis zur Rückkehr gesperrt.');next='mission';}
    if(next==='hq')history=[];
    if(push&&view!==next&&next!=='hq')history.push({view,context:{...G.context},extraType,replacement,index});
    G.context={...G.context,...ctx};
    if(['stash','shop','gear'].includes(next))G.context={...G.context,armoryTarget:'all'};
    if(!G.activeHunter()&&G.state.roster.length)selectHunter(G.state.roster[0].id);
    if(next!=='armory')replacement=null;
    view=next;
    document.querySelectorAll('.screen').forEach(n=>n.classList.toggle('active',n.id==='screen-'+view));
    $('#backBtn').classList.toggle('hidden',view==='hq');
    $('#pageEyebrow').textContent='RPG HUNT / '+routes[view].toUpperCase();
    $('#pageTitle').textContent=G.state.run&&view==='mission'?'Jagd im Gange':routes[view];
    renderCurrent();decorateMenu();window.scrollTo({top:0,behavior:'instant'});
    if(view==='hq'&&G.state.run)G.toast('Dein Run läuft weiter. Über Mission kehrst du zurück.');
  }
  function back(){
    if(!$('#modal').classList.contains('hidden')){G.closeModal();return;}
    const p=history.pop();if(p){G.context=p.context;extraType=p.extraType;replacement=p.replacement;index=p.index;navigate(p.view,{},false);}else navigate('hq',{},false);
  }
  function renderCurrent(){const fn={hq:renderHQ,hunters:renderHunters,recruit:renderRecruitment,roster:renderRoster,hunterDetail:renderHunterDetail,gear:legacy.renderGearHub,loadout:renderLoadout,armory:renderArmory,shop:renderShop,stash:renderStash,traits:renderTraits,mission:renderMission,codex:legacy.renderCodex,stats:renderStats,settings:legacy.renderSettings}[view];fn?.();}
  function teamSlots(){const team=G.state.selectedTeam.map(id=>G.state.roster.find(h=>h.id===id)).filter(Boolean);return [0,1,2].map(i=>{const h=team[i];return `<article class="v6-team-slot">${h?`<img loading="lazy" decoding="async" src="${G.portraitArt(h)}" alt=""><div><small>SLOT 0${i+1} · ${esc(h.tier)}</small><h3>${esc(h.name)}</h3><p>${esc(h.primary?.name||h.sidearm?.name||'Unbewaffnet')}</p><p>${esc(h.sidearm?.name||'Keine Seitenwaffe')} · ${h.extras.length}/8 Extras</p><div class="v6-team-weapons">${[h.primary,h.sidearm].filter(Boolean).map(w=>`<figure><img loading="lazy" decoding="async" src="${G.weaponArt(w)}" alt="${esc(w.name)}"><figcaption>${esc(w.name)} · ${esc(S.selected(G.state,w).name)}</figcaption></figure>`).join('')}</div>${btn('Details',`data-openhunter="${h.id}"`)}${btn('Aus Team',`data-team="${h.id}"`,!!G.state.run)}</div>`:`<span class="empty-slot-number">0${i+1}</span><div><small>FREIER TEAMPLATZ</small>${btn('Hunter wählen','data-nav="roster"',!!G.state.run)}</div>`}</article>`;}).join('');}
  function renderHQ(){legacy.renderHQ();$('#hqTeam').innerHTML=teamSlots();$('#screen-hq [data-nav="mission"] .tile-kicker').textContent=G.state.run?'01 / RUN FORTSETZEN':'01 / AUFTRAG';}
  function statGrid(h){return `<dl class="v6-stats">${[['Leben',`${h.hp}/${h.maxHp}`],['Präzision',h.accuracy],['Stärke',h.strength],['Tempo',h.speed],['Ausdauer',h.maxStamina],['Glück',h.luck]].map(([n,v])=>`<div><dt>${n}</dt><dd>${v}</dd></div>`).join('')}</dl>`;}
  function hunterCard(h,marketMode=false){const owned=G.state.selectedTeam.includes(h.id);return `<article class="v6-hunter tier-${h.tier} ${owned?'in-team':''}"><button class="v6-portrait" data-openhunter="${h.id}" aria-label="${esc(h.name)} Details"><img loading="lazy" decoding="async" src="${G.portraitArt(h)}" alt="${esc(h.name)}"><span class="tier-chip">${h.tier}</span><span class="portrait-level">LEVEL ${h.level}</span></button><div class="v6-card-copy"><p class="eyebrow">${esc(h.role)} · ${owned?'IM TEAM':h.hp>0?'BEREIT':'GEFALLEN'}</p><h2>${esc(h.name)}</h2>${statGrid(h)}<p class="v6-ai">${esc(h.ai?.profile||'Hunter')} · Intelligenz ${h.ai?.intelligence||'–'}</p><div class="v6-kit"><span>Primär</span><b>${esc(h.primary?.name||'Nicht ausgerüstet')}</b><span>Sekundär</span><b>${esc(h.sidearm?.name||'Nicht ausgerüstet')}</b><span>Extras</span><b>${esc(h.extras.map(x=>x.name).join(', ')||'Keine')}</b><span>Traits</span><b>${esc(h.perks.map(i=>window.RPG_HUNT_ART?.traitName(D.PERKS[i])||D.PERKS[i]?.name).filter(Boolean).join(', ')||'Keine')}</b></div><div class="v6-card-actions">${marketMode?`<strong class="price ${G.state.money<h.price?'unaffordable':''}">${cash(h.price)}</strong>${btn('Rekrutieren',`data-recruit="${h.id}"`,G.state.money<h.price)}`:`${btn(owned?'Im Team · entfernen':'Ins Team',`data-team="${h.id}"`,!!G.state.run)}${btn('Details',`data-openhunter="${h.id}"`)}`}</div></div></article>`;}
  function renderRecruitment(){if(!G.market.length)G.rerollMarket(false);$('#recruitMarket').innerHTML=G.market.map(h=>hunterCard(h,true)).join('');$('#rerollHunters').disabled=G.state.money<100;}
  function previewRecruit(id){const h=G.market.find(h=>h.id===id);if(h)G.openModal('<div class="v6-recruit-detail">'+hunterCard(h,true)+'</div>');}
  function renderRoster(){const q=$('#rosterSearch').value.toLowerCase(),tier=$('#rosterTier').value;const list=G.state.roster.filter(h=>(!q||`${h.name} ${h.role}`.toLowerCase().includes(q))&&(!tier||h.tier===tier));$('#roster').innerHTML=list.map(h=>hunterCard(h)).join('')||empty('Keine passenden Hunter. '+btn('Rekrutierung','data-nav="recruit"'));}
  function renderHunters(){$('#hunterHubCards').innerHTML=G.state.roster.slice(0,4).map(h=>`<button class="v6-hunter-chip" data-openhunter="${h.id}"><img loading="lazy" decoding="async" src="${G.portraitArt(h)}" alt=""><span>${esc(h.name)}<small>${h.tier} · Level ${h.level}</small></span></button>`).join('');}
  function switcher(h){return `<div class="v6-switcher">${btn('‹','data-v6-hunter="-1" aria-label="Vorheriger Hunter"',G.state.roster.length<2)}<img loading="lazy" decoding="async" src="${G.portraitArt(h)}" alt=""><div><p class="eyebrow">${esc(h.tier)} · LEVEL ${h.level}</p><h2>${esc(h.name)}</h2></div>${btn('›','data-v6-hunter="1" aria-label="Nächster Hunter"',G.state.roster.length<2)}</div>`;}
  function renderHunterDetail(){legacy.renderHunterDetail();const h=G.activeHunter();if(!h)return;$('#hunterDetail').insertAdjacentHTML('afterbegin',switcher(h));$('#hunterDetail').insertAdjacentHTML('beforeend',`<section class="v6-ai-profile panel"><p class="eyebrow">AUTONOME HUNTER-KI</p><h2>${esc(h.ai.profile)}</h2><p>${esc(G.aiBehaviourText(h))}</p><dl class="v6-stats">${Object.entries({Intelligenz:h.ai.intelligence,Disziplin:h.ai.discipline,Aggression:h.ai.aggression,Mut:h.ai.courage}).map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')}</dl></section>`);}
  function renderLoadout(){const h=G.activeHunter();if(!h){$('#loadoutView').innerHTML=empty('Wähle einen Hunter. '+btn('Hunter','data-nav="roster"'));return;}$('#loadoutView').innerHTML=`${switcher(h)}<div class="v6-loadout"><aside><img class="v6-full-portrait" src="${G.portraitArt(h)}" alt="${esc(h.name)}"><p class="eyebrow">${esc(h.ai.profile)}</p><p>Waffen wechseln ohne Verlust: Deine bisherige Ausrüstung geht ins Lager.</p>${btn('Lager öffnen','data-nav="stash"')}${btn('Traits',`data-opentraits="${h.id}"`)}</aside><div><div class="v6-weapon-slots">${['primary','sidearm'].map((slot,i)=>{const w=h[slot];return `<article class="v6-slot"><button data-openarmory="${slot}" class="v6-slot-art"><img loading="lazy" decoding="async" src="${G.weaponArt(w)}" alt="${esc(w?.name||'Leerer Slot')}"><span>${i?'SEKUNDÄRWAFFE':'PRIMÄRWAFFE'}</span></button><div><h2>${esc(w?.name||'Leerer Slot')}</h2><p>${w?`${esc(w.quality)} · Schaden ${w.damage} · Präzision ${w.accuracy}`:'Passende Waffe auswählen'}</p>${btn('Waffe wählen',`data-openarmory="${slot}"`)}${skinPicker(w)}${w?btn('Ins Lager',`data-unequipweapon="${slot}"`):''}</div></article>`;}).join('')}</div>${['tool','consumable'].map(type=>{const list=h.extras.map((x,i)=>({x,i})).filter(({x})=>(x.type==='tool'?'tool':'consumable')===type);return `<section class="v6-extra-section"><h2>${type==='tool'?'Tools':'Consumables'} <small>${list.length} belegt</small></h2><div class="v6-extra-slots">${Array.from({length:Math.max(4,list.length)},(_,n)=>{const entry=list[n],x=entry?.x;return `<article class="v6-extra-slot"><button data-v6-extra="${type}" data-replace="${entry?.i??''}"><img loading="lazy" decoding="async" src="${G.extraArt(x||{name:type==='tool'?'knife':'shot'})}" alt=""><small>${type==='tool'?'TOOL':'CONSUMABLE'} ${n+1}</small><b>${esc(x?.name||'Slot belegen')}</b><span>${x?`${x.currentUses===99?'∞':x.currentUses} Einsätze`:'Auswahl öffnen'}</span></button>${skinPicker(x)}${x?btn('Ins Lager',`data-unequipextra="${entry.i}"`):''}</article>`;}).join('')}</div></section>`;}).join('')}<p class="muted">${h.extras.length}/8 gemeinsame Extraslots. Die flexible v0.5-Kapazität bleibt erhalten; Tools und Consumables werden getrennt angezeigt.</p></div></div>`;}
  function family(w){return w.category==='Melee'?'melee':w.category==='Shotgun'?'shotguns':G.weaponSlot(w)==='sidearm'?'pistols':/Special|Bow|Crossbow/.test(w.category)?'special':'rifles';}
  function weaponList(){const target=G.context.armoryTarget||'all',q=$('#weaponSearch').value.toLowerCase(),c=$('#weaponCategory').value,quality=$('#weaponQuality').value,f=$('#weaponFamily').value,source=$('#weaponSource').value;const list=D.WEAPONS.filter(w=>(target==='all'||G.weaponSlot(w)===target)&&(!q||`${w.name} ${w.family}`.toLowerCase().includes(q))&&(!c||w.category===c)&&(!quality||w.quality===quality)&&(f==='all'||family(w)===f)&&(source!=='owned'||G.state.stashWeapons.some(x=>x.name===w.name)));const sort=$('#weaponSort').value;const ranks=['Gewöhnlich','Ungewöhnlich','Selten','Episch','Legendär'];return list.sort((a,b)=>(sort==='damage'?b.damage-a.damage:sort==='accuracy'?b.accuracy-a.accuracy:sort==='quality'?ranks.indexOf(b.quality)-ranks.indexOf(a.quality):a.price-b.price)||a.name.localeCompare(b.name));}
  function weaponStage(list,merchant=false){if(!list.length)return empty('Keine Waffen für diese Filter.');let selected=merchant?shopIndex:index;selected=((selected%list.length)+list.length)%list.length;if(merchant)shopIndex=selected;else index=selected;const w=list[selected],stash=G.state.stashWeapons.findIndex(x=>x.name===w.name),h=G.activeHunter();return `<section class="v6-weapon-stage"><div class="v6-weapon-display">${btn('‹',`data-v6-weapon="-1" data-merchant="${merchant}" aria-label="Vorherige Waffe"`)}<img loading="lazy" decoding="async" src="${G.weaponArt(w)}" alt="${esc(w.name)}">${btn('›',`data-v6-weapon="1" data-merchant="${merchant}" aria-label="Nächste Waffe"`)}</div><div class="v6-weapon-data"><p class="eyebrow">${esc(w.category)} / ${esc(w.ammo)} / ${esc(w.quality)}</p><h2>${esc(w.name)}</h2><p>${esc(w.special||'Bereit für die Jagd.')}</p>${skinPicker(w)}<dl class="v6-stats">${[['Schaden',w.damage],['Maximum',w.damageMax],['Präzision',w.accuracy],['Magazin',w.mag],['Kontrolle',w.control],['Nah / Mittel / Fern',`${w.near} / ${w.mid} / ${w.far}`],['Lautstärke',w.noise],['Munition',w.ammo]].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl><p class="muted">Schaden pro Angriffsaktion. Trefferchance im Kampf: 35–95 %.</p><div class="v6-card-actions"><strong class="price">${cash(w.price)}</strong>${merchant?btn('Kaufen → Lager',`data-shop-buystash="${esc(w.name)}"`,G.state.money<w.price):stash>=0?btn('Kostenlos ausrüsten',`data-equipstashweapon="${stash}"`,!h):btn('Kaufen & ausrüsten',`data-buyweapon="${esc(w.name)}"`,!h||G.state.money<w.price)}</div><small>${selected+1} / ${list.length} · ${stash>=0?'Im Lager vorhanden':'Händlerbestand'}</small></div></section><div class="v6-thumbnails">${list.map((x,i)=>`<button class="${i===selected?'active':''}" data-v6-select="${i}" data-merchant="${merchant}" aria-label="${esc(x.name)}"><img loading="lazy" decoding="async" src="${G.weaponArt(x)}" alt=""><span>${esc(x.name)}</span><small>${cash(x.price)}</small></button>`).join('')}</div>`;}
  function renderArmory(){G.weaponFilters();const extras=G.armoryMode==='extras';$('#armoryTitle').textContent=extras?'Tools & Consumables':G.context.armoryTarget==='primary'?'Primärwaffe auswählen':G.context.armoryTarget==='sidearm'?'Sekundärwaffe auswählen':'Das Arsenal';$('#activeBuyer').textContent=G.activeHunter()?.name||'Kein Hunter gewählt';$('#armoryHint').textContent='Besitz bleibt Besitz. Eingelagerte Ausrüstung kostet dich keinen Dollar.';$('#weaponList').classList.toggle('hidden',extras);$('#extraList').classList.toggle('hidden',!extras);$('#weaponPagination').innerHTML='';$('#stashWeaponStrip').innerHTML='';controls.forEach(id=>$('#'+id).classList.toggle('hidden',extras&&id!=='weaponSearch'));$('#armoryWeaponsBtn').classList.toggle('active',!extras);$('#armoryExtrasBtn').classList.toggle('active',extras);if(extras)renderExtras();else $('#weaponList').innerHTML=weaponStage(weaponList());}
  function renderExtras(){const h=G.activeHunter(),q=$('#weaponSearch').value.toLowerCase();$('#extraList').innerHTML=`<div class="v6-filter-tabs">${['all','tool','consumable'].map((x,i)=>btn(['Alle','Tools','Consumables'][i],`data-v6-extra-filter="${x}"`)).join('')}</div><div class="v6-item-grid">${D.EXTRAS.map((x,i)=>({x,i})).filter(({x})=>(extraType==='all'||(x.type==='tool'?'tool':'consumable')===extraType)&&(!q||`${x.name} ${x.text}`.toLowerCase().includes(q))).map(({x,i})=>{const si=G.state.stashExtras.findIndex(y=>y.name===x.name);return `<article class="v6-item"><img loading="lazy" decoding="async" src="${G.extraArt(x)}" alt="${esc(x.name)}"><div><p class="eyebrow">${esc(x.type)} · ${x.uses===99?'∞':x.uses} Einsätze</p><h3>${esc(x.name)}</h3><p>${esc(x.text)}</p><strong class="price">${cash(x.price)}</strong>${skinPicker(x)}${btn(si>=0?'Aus Lager ausrüsten':'Kaufen & ausrüsten',`data-v6-equip-extra="${i}"`,!h||(si<0&&G.state.money<x.price)||(h?.extras.length>=8&&replacement===null))}</div></article>`;}).join('')}</div>`;}
  function equipExtra(i){const h=G.activeHunter(),x=D.EXTRAS[i];if(!h||!x||G.state.run)return;const si=G.state.stashExtras.findIndex(y=>y.name===x.name);if(si<0&&G.state.money<x.price)return;if(replacement!==null&&h.extras[replacement])G.unequipExtra(replacement);if(si>=0)G.equipStashExtra(si);else G.buyExtra(i);replacement=null;renderArmory();}
  function renderShop(){G.shopInitFilters();$('#shopBuyerBox').innerHTML=`<p class="eyebrow">DEIN KONTO</p><h2>${cash(G.state.money)}</h2>${btn('Zum Lager','data-nav="stash"')}`;document.querySelectorAll('[data-v6-shop]').forEach(b=>b.classList.toggle('active',b.dataset.v6Shop===shopMode));const q=$('#shopSearch').value.toLowerCase();if(shopMode==='weapons'||shopMode==='offers'){$('#shopContent').innerHTML=weaponStage(G.shopWeaponList().sort((a,b)=>a.price-b.price).filter(w=>shopMode!=='offers'||w.price<=300),true);return;}const list=D.EXTRAS.map((x,i)=>({x,i})).filter(({x})=>(shopMode==='ammo'?/ammo/i.test(x.name):shopMode==='tools'?x.type==='tool':x.type!=='tool')&&(!q||`${x.name} ${x.text}`.toLowerCase().includes(q)));$('#shopContent').innerHTML=`${shopMode==='ammo'?'<p class="muted">Vorhandene Munitions-Extras. Das Kampfsystem benötigt keine separat gekauften Patronen.</p>':''}<div class="v6-item-grid">${list.map(({x,i})=>`<article class="v6-item"><img loading="lazy" decoding="async" src="${G.extraArt(x)}" alt=""><div><p class="eyebrow">${esc(x.type)}</p><h2>${esc(x.name)}</h2><p>${esc(x.text)}</p><strong class="price">${cash(x.price)}</strong>${skinPicker(x)}${btn('Kaufen → Lager',`data-shop-extra-stash="${i}"`,G.state.money<x.price)}</div></article>`).join('')||empty('Keine passenden Waren.')}</div>`;}
  function renderStash(){const h=G.activeHunter();$('#screen-stash').innerHTML=`${title('GEMEINSAMER BESITZ','Die Vorratskammer','Einlagern. Wieder ausrüsten. Überleben.')}<div class="v6-stash-header">${h?switcher(h):btn('Hunter wählen','data-nav="roster"')}<p>Verkauf: 55 % des ursprünglichen Preises. Ausrüsten aus dem Lager ist kostenlos.</p></div><div class="v6-filter-tabs">${['weapons','tools','consumables','other'].map((x,i)=>btn(['Waffen','Tools','Consumables','Sonstiges'][i],`data-v6-stash="${x}"`)).join('')}</div><div class="v6-item-grid">${(stashMode==='weapons'?G.state.stashWeapons:G.state.stashExtras).map((x,i)=>({x,i})).filter(({x})=>stashMode==='weapons'||stashMode==='tools'&&x.type==='tool'||stashMode==='consumables'&&x.type!=='tool').map(({x,i})=>`<article class="v6-item"><img loading="lazy" decoding="async" src="${stashMode==='weapons'?G.weaponArt(x):G.extraArt(x)}" alt=""><div><p class="eyebrow">${esc(x.category||x.type)}</p><h2>${esc(x.name)}</h2><p>${esc(x.special||x.text||'')}${stashMode==='weapons'?` · Schaden ${x.damage} · Präzision ${x.accuracy}`:` · ${x.currentUses} Einsätze`}</p>${skinPicker(x)}${btn('Kostenlos ausrüsten',`${stashMode==='weapons'?'data-equipstashweapon':'data-equipstashextra'}="${i}"`,!h||stashMode!=='weapons'&&h.extras.length>=8)}${btn(`Verkaufen · ${cash(G.sellValue(x.price))}`,`data-v6-sell="${i}" data-kind="${stashMode==='weapons'?'weapon':'extra'}"`)}</div></article>`).join('')||empty('Hier liegt noch keine Ausrüstung. '+btn('Zum Händler','data-nav="shop"'))}</div>`;}
  function renderTraits(){legacy.renderTraits();const h=G.activeHunter();if(!h)return;const ps=h.perks.map(i=>D.PERKS[i]).filter(Boolean);$('#traitBuyer').textContent=`${h.name} · ${h.upgradePoints||0} UP · ${ps.length}/15 Traits · ${ps.reduce((s,p)=>s+p.weight,0)}/24 Gewicht · ${ps.filter(p=>p.rarity==='schwer').length}/5 schwer · ${ps.filter(p=>p.rarity==='mythic').length}/2 Mythic`;document.querySelectorAll('[data-buytrait]').forEach(b=>{const p=D.PERKS[+b.dataset.buytrait];b.disabled=!G.canAddPerk(h,p)||(h.upgradePoints||0)<G.perkCost(p);});}
  function renderMission(){legacy.renderMission();if(G.state.run)return;$('#missionTeam').innerHTML=teamSlots();const c=G.ensureContract(),env=V.environments.find(e=>e.id===c.envId)||V.environments[0],team=G.state.selectedTeam.map(id=>G.state.roster.find(h=>h.id===id)).filter(Boolean);$('#screen-mission .brief-art').style.backgroundImage=`url('${env.art}')`;$('#contractDetails').insertAdjacentHTML('beforeend',`<div><span>Bossrisiko</span><b>Hoch · ${esc(c.target)}</b></div><div><span>Teamstärke (Orientierung)</span><b>${team.reduce((s,h)=>s+h.maxHp+h.accuracy+(h.primary?.damage||h.sidearm?.damage||0),0)}</b></div><div><span>Ausrüstungswert</span><b>${cash(team.reduce((s,h)=>s+(h.primary?.price||0)+(h.sidearm?.price||0)+h.extras.reduce((a,x)=>a+x.price,0),0))}</b></div>`);$('#startRunBtn').disabled=!team.length||team.some(h=>!h.primary&&!h.sidearm);$('#startRunBtn').textContent=team.some(h=>!h.primary&&!h.sidearm)?'Hunter zuerst bewaffnen':'Mission starten';}
  function renderStats(){const s=G.state;$('#screen-stats').innerHTML=title('JAGDBUCH','Was von dir bleibt','Jeder Heimweg zählt.')+`<div class="v6-stat-board">${Object.entries({Missionen:s.stats.runs,Extraktionen:s.stats.extracts,Bosse:s.stats.bosses,Verluste:s.stats.losses,'Hunter im Roster':s.roster.length,'Kills der aktuellen Hunter':s.roster.reduce((n,h)=>n+(h.kills||0),0)}).map(([k,v])=>`<article class="panel"><p class="eyebrow">${k}</p><strong>${v||0}</strong></article>`).join('')}</div><article class="panel"><h2>Letzter Run</h2><p>${s.lastRun?`${s.lastRun.success?'Extrahiert':'Verloren'} · ${s.lastRun.rounds} Runden · ${cash(s.lastRun.loot)}`:'Noch kein Run abgeschlossen.'}</p></article>`;}
  function refresh(){renderHunters();if(view==='stash')renderStash();if(view==='stats')renderStats();decorateMenu();}
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();back();}});
  document.addEventListener('click',e=>{
    const b=e.target.closest('button');if(!b||b.disabled)return;
    const data=b.dataset;
    if(b.matches('[data-openarmory],[data-openextras]')){index=0;replacement=null;extraType='all';$('#weaponSearch').value='';}

    const managed=['v6Skin','v6Hunter','v6Weapon','v6Select','v6Extra','v6ExtraFilter','v6EquipExtra','v6Shop','v6Stash','v6Sell','v6Confirm','v6Cancel'].some(k=>k in data);
    if(G.state.run&&(managed||b.matches('[data-buyweapon],[data-buyextra],[data-equipstashweapon],[data-equipstashextra],[data-recruit],[data-unequipweapon],[data-unequipextra],[data-buytrait],[data-shop-buystash],[data-shop-extra-stash]'))){e.stopImmediatePropagation();G.toast('Während einer Mission gesperrt.');return;}
    if(!managed)return;e.preventDefault();e.stopImmediatePropagation();
    if('v6Skin'in data){const w=[...D.WEAPONS,...D.EXTRAS].find(x=>x.name===data.skinWeapon);if(w&&S.cycle(G.state,w,Number(data.v6Skin))){G.save();renderCurrent();decorateMenu();}}
    if('v6Hunter'in data){const list=G.state.roster,i=list.findIndex(h=>h.id===G.activeHunter()?.id);if(list.length){selectHunter(list[(i+Number(data.v6Hunter)+list.length)%list.length].id);replacement=null;renderCurrent();G.save();}}
    if('v6Weapon'in data){if(data.merchant==='true'){shopIndex+=Number(data.v6Weapon);renderShop();}else{index+=Number(data.v6Weapon);renderArmory();}}
    if('v6Select'in data){if(data.merchant==='true'){shopIndex=Number(data.v6Select);renderShop();}else{index=Number(data.v6Select);renderArmory();}}
    if('v6Extra'in data){$('#weaponSearch').value='';extraType=data.v6Extra;replacement=data.replace===''?null:Number(data.replace);G.armoryMode='extras';navigate('armory');}
    if('v6ExtraFilter'in data){extraType=data.v6ExtraFilter;renderExtras();}
    if('v6EquipExtra'in data)equipExtra(Number(data.v6EquipExtra));
    if('v6Shop'in data){shopMode=data.v6Shop;shopIndex=0;renderShop();}
    if('v6Stash'in data){stashMode=data.v6Stash;renderStash();}
    if('v6Sell'in data){const idx=Number(data.v6Sell),weapon=data.kind==='weapon',item=(weapon?G.state.stashWeapons:G.state.stashExtras)[idx];if(!item)return;confirmation=()=>{const list=weapon?G.state.stashWeapons:G.state.stashExtras,i=list.indexOf(item);if(i>=0)(weapon?G.sellStashWeapon:G.sellStashExtra)(i);renderStash();};G.openModal(`<p class="eyebrow">VERKAUF BESTÄTIGEN</p><h2>${esc(item.name)}</h2><p>Für ${cash(G.sellValue(item.price))} verkaufen?</p><div class="v6-card-actions">${btn('Abbrechen','data-v6-cancel')}${btn('Verkaufen','data-v6-confirm')}</div>`);}
    if('v6Cancel'in data){confirmation=null;G.closeModal();}
    if('v6Confirm'in data){const fn=confirmation;confirmation=null;G.closeModal();fn?.();}
    decorateMenu();
  },true);
  return {navigate,back,refresh,renderHQ,renderRecruitment,renderRoster,renderHunterDetail,renderLoadout,renderArmory,renderShop,renderTraits,renderMission,hunterCard,previewRecruit};
};
